#cloud-config

apt_update: true
apt_upgrade: true

packages:
  - docker-compose
  - git-lfs

runcmd:
  - git clone https://github.com/scaleoutsystems/fedn.git
  - cd fedn/
  - cp config/settings-combiner.yaml.template config/settings-combiner.yaml
  - screen -S combiner docker-compose -f config/combiner.yaml up
