#cloud-config

apt_update: true
apt_upgrade: true

packages:
  - docker-compose
  - git-lfs

fqdn: combiner

runcmd:
  - cd /home/ubuntu/
  - git clone https://github.com/scaleoutsystems/fedn.git
  - cd fedn/
  - cp config/settings-combiner.yaml.template config/settings-combiner.yaml
  - cp config/combiner.yaml docker-compose.yaml
  - docker-compose up
