#cloud-config

apt_update: true
apt_upgrade: false

packages:
  - docker-compose
  - git-lfs

fqdn: combinerTest
write_files:
  - path: /home/ubuntu/extra-hosts-combiner.yaml
    content: |
      version: '3.3'
      services:
        reducer:
          extra_hosts:
            group4_test_reducer: 192.168.199.81
  - path: /home/ubuntu/settings-combiner.yaml
    content: |
     network_id: fedn-test-network
     controller:
       discover_host: group4_test_reducer
       discover_port: 8090
       token: token

     combiner:
       name: combiner
       host: combiner
       port: 12080
       max_clients: 30
     statestore:
       type: MongoDB
       mongo_config:
         username: fedn_admin
         password: owr3fwoja09oj
         host: group4_test_reducer
         port: 6534

     storage:
       storage_type: S3
       storage_config:
         storage_hostname: group4_test_reducer 
         storage_port: 9000
         storage_access_key: fedn_admin
         storage_secret_key: ieojf3faw4a3
         storage_bucket: fedn-models
         context_bucket: fedn-context
         storage_secure_mode: False


runcmd:
  - cd /home/ubuntu/
  - git clone https://github.com/scaleoutsystems/fedn.git
  - cd fedn/
  - cp /home/ubuntu/settings-combiner.yaml config/settings-combiner.yaml
  - cp config/combiner.yaml docker-compose.yaml
  - docker-compose up
